name: CMake-Release

on:
  release:
    types: [prereleased]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # The number of days to retain artifacts
  RETENTION_DAYS: 30

jobs:

  build-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake MSVC
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G"Visual Studio 16 2019"
      - name: Build MSVC
        run: |
          cmake --build build --target GenerateEPKS
          cmake --build build --config ${{env.BUILD_TYPE}}
      - uses: actions/upload-artifact@v3
        with:
          name: edge-classic-msvc
          path: |
            autoload
            docs
            edge_base/*.epk
            edge_fixes
            soundfont
            edge-classic.exe
            *.dll
            *.epk
            CHANGELOG.md
          retention-days: ${{env.RETENTION_DAYS}}      